### ISSUE TITLE
Update HG version in resumable docker

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/hgresume#8]
The current version in the docker container is 5.61, but we need it to be 5.7+ for our current setup.

**Comment by rmunn** [comment]
Might be as simple as basing the container off of Debian 12, which is set to release in a few days. Otherwise we'll need to do something clever with installing Mercurial through pip similar to what's being done in https://github.com/sillsdev/languageforge-lexbox/pull/79/commits/ed37b49f7e34215c040d1730a5cd85cc0d07395f.

**Comment by hahn-kev** [comment]
closed in fec78c3
